---
flickr:
  api_key: 6b3bdebf50c0a624eb7ec35c5acf2d8f
  shared_secret: 4bb9d1f00accca46
  access_token: 72157651440202028-627f38a243925eeb
  access_secret: 77459e600d1ab808
__comment_on_flickr_creds__: when adding a new user, only api_key and shared_secret
  are needed
work_dirs:
- "/Volumes/Elements/PHOTOS"
__comment_on_work_dirs__:
- must be full path starting at '/'
- no importance for '/' at the end
