work_dirs:
  - "/Users/amir/Pictures"
__comment__:
  - "must be full path starting at '/'"
  - "no importance for '/' at the end"
  - "/Users/amir/Pictures"
  - "Mehler - old scans/wedding"
  - "/Volumes/Elements/PHOTOS"
